spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management_prod
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
jwt:
  secret: ------secret-key--------
  expiration: 360000000