spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management_dev
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: ------secret-key--------
  expiration: 360000000